# ensemble.GradientBoostingClassifier

In [1]:
%config IPCompleter.greedy=True

In [2]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [3]:
from sklearn import ensemble
import numpy as np
import pandas as pd
import sys
import pickle
import csv

# Database_Sentence_Kannada_680_Samples

In [4]:
path_to_data = '/home/lenovo/All5_KannadaDataAug2018/5_Class_Sentc_Knd_Extracd_Features/'

max_classes = 5;
#Don't Edit this Below Code
max_classes += 1;

##### Read the file.csv  in Text Mode
- mode='rt' or mode='r'


Here, Read the file.csv  in Text Mode to Extract the Contents in it using above code.
      

In [5]:
X_mfcc = []
Y_mfcc = []

## CSV Not With PICKLE(PYTHON_eNCODING format)
- If the CSV file is Not Generated using PICKLE then to OPEN the file is the following way:

with open(path_to_data + 'MFCC_Features/MFCC_features_' + str(max_classes-1) + '.csv',mode='rt') as fp: 
    X_Mfccs= csv.reader(fp, delimiter=',',quotechar='|')
    
    for row in X_Mfccs:
        if len(row)!= 0:
            X_mfcc = X_mfcc + [row]
        
    print(fp.closed)
with open(path_to_data + 'MFCC_Features/MFCC_labels_' + str(max_classes-1) + '.csv',mode='rt') as fp:
    y_labels = csv.reader(fp, delimiter=',',quotechar='|')
    
    for row in y_labels:
        if len(row)!= 0:
            Y_mfcc = Y_mfcc + [row]
        
    print(fp.closed)

#### Error - while trying to Open a "(pickle)"- Encoded CSV file
 If U are trying to Open a "(pickle)"- Encoded CSV file, then this Error will Arise:
- UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte


## Opening CSV file Encoded using "PICKLE"_PYTHON Encoding

## MFCC__Features

#### Path_to_Features for Loading

In [6]:
with open(path_to_data + 'MFCC_Features/MFCC_labels_680_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_mfcc= pickle.load(fp)

    
with open(path_to_data + 'MFCC_Features/MFCC_features_680_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_mfcc= pickle.load(fp,encoding='latin1') 

In [7]:
X_fs = np.array(X_mfcc)
Y_ls = np.array(y_mfcc)

In [8]:
X_fs.shape, Y_ls.shape

((680, 40), (680,))

#### Splitting Data for TRAINing & TESTing

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_fs,Y_ls, test_size=0.3,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((476, 40), (476,), (204, 40), (204,))

### SGD Models (for Classification of Dialects)

- loss = 'deviance'

In [11]:
cv_clf = ensemble.GradientBoostingClassifier(loss = 'deviance') # exponential
scores_egb_d =cross_val_score(cv_clf,X_fs,Y_ls, cv=2)

scores_egb_d

array([ 0.90322581,  0.91740413])

In [13]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_egb_d.mean(), scores_egb_d.std() * 2))

Accuracy: 0.91 (+/- 0.01)


- loss = 'exponential'
  This is NOT Acceptable, bcoz ValueError: ExponentialLoss requires 2 classes.

In [15]:
cv_clf = ensemble.GradientBoostingClassifier(loss = 'deviance')
scores_egb_d_cv =cross_val_score(cv_clf,X_fs,Y_ls, cv=10)

scores_egb_d_cv



array([ 0.9       ,  0.95652174,  0.92753623,  0.91304348,  0.86764706,
        0.95588235,  0.95522388,  0.98507463,  0.89552239,  0.92424242])

In [16]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_egb_d_cv.mean(), scores_egb_d_cv.std() * 2))

Accuracy: 0.93 (+/- 0.07)


## Delta_mfcc Features Path

#### Path_to_Features for Loading

In [17]:
with open(path_to_data + 'MFCC_Features/delta_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_delta = pickle.load(fp)
with open(path_to_data + 'MFCC_Features/delta_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_delta = pickle.load(fp,encoding='latin1')

In [18]:
X_Dmfs = np.array(X_delta)
Y_Dls = np.array(y_delta)

In [19]:
X_Dmfs.shape, Y_Dls.shape

((653, 40), (653,))

#### Splitting Data for TRAINing & TESTing

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_Dmfs,Y_Dls, test_size=0.3,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((457, 40), (457,), (196, 40), (196,))

### EGB Model (for Classification of Dialects)

- loss="deviance"

In [20]:
D_m_clf = ensemble.GradientBoostingClassifier(loss = 'deviance')
scores_egb_dm =cross_val_score(D_m_clf,X_Dmfs,Y_Dls, cv=10)

scores_egb_dm

array([ 0.69117647,  0.8030303 ,  0.78787879,  0.78787879,  0.81538462,
        0.76923077,  0.8       ,  0.703125  ,  0.703125  ,  0.75      ])

In [22]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_egb_dm.mean(), scores_egb_dm.std() * 2))

Accuracy: 0.76 (+/- 0.09)


## Delta_Delta_mfcc Features

#### Path_to_Features for Loading

In [18]:
with open(path_to_data + 'MFCC_Features/delta2_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_delta2 = pickle.load(fp)

with open(path_to_data + 'MFCC_Features/delta2_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_delta2 = pickle.load(fp,encoding='latin1')

In [19]:
X_DDmfs = np.array(X_delta2)
Y_DDls = np.array(y_delta2)

In [20]:
X_DDmfs.shape, Y_DDls.shape

((653, 40), (653,))

#### Splitting Data for TRAINing & TESTing

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X_DDmfs,Y_DDls, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((522, 40), (522,), (131, 40), (131,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [63]:
clf_fold = SGDClassifier(loss="modified_huber", penalty="l2")

scores_sgd_dd =cross_val_score(clf_fold,X_DDmfs,Y_DDls, cv=10)

scores_sgd_dd

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.51470588,  0.74242424,  0.77272727,  0.65151515,  0.64615385,
        0.67692308,  0.6       ,  0.484375  ,  0.453125  ,  0.578125  ])

In [64]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_sgd_dd.mean(), scores_sgd_dd.std() * 2))

Accuracy: 0.61 (+/- 0.20)


## MelSpectrogram Features

#### Path_to_Features for Loading

In [60]:
with open(path_to_data + 'MelSpec_Features/Mel_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_mel= pickle.load(fp)
    
with open(path_to_data + 'MelSpec_Features/Mel_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_mel= pickle.load(fp,encoding='latin1') 

- Radial basis function - "rbf" Kernel

In [29]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm =cross_val_score(clf_rbf,X_Dmfs,Y_Dls, cv=10)

scores_rbf_svm

array([ 0.67647059,  0.84848485,  0.74242424,  0.78787879,  0.78461538,
        0.78461538,  0.81538462,  0.703125  ,  0.71875   ,  0.703125  ])

In [30]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm.mean(), scores_rbf_svm.std() * 2))

Accuracy: 0.76 (+/- 0.11)


In [61]:
X_melfs = np.array(X_mel)
Y_mels = np.array(y_mel)

In [62]:
X_melfs.shape, Y_mels.shape

((1574, 128), (1574,))

#### Splitting Data for TRAINing & TESTing

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X_melfs,Y_mels, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((1259, 128), (1259,), (315, 128), (315,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [65]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm =cross_val_score(clf_fold,X_melfs,Y_mels, cv=10)

scores_lsvm

array([ 0.3125    ,  0.24375   ,  0.3       ,  0.34591195,  0.29299363,
        0.32051282,  0.30128205,  0.35897436,  0.42580645,  0.33548387])

In [66]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm.mean(), scores_lsvm.std() * 2))

Accuracy: 0.32 (+/- 0.09)


- Radial basis function - "rbf" Kernel

In [69]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm_melS =cross_val_score(clf_rbf,X_melfs,Y_mels, cv=10)

scores_rbf_svm_melS

array([ 0.2875    ,  0.3       ,  0.28125   ,  0.41509434,  0.33121019,
        0.30769231,  0.30769231,  0.34615385,  0.30967742,  0.30967742])

In [70]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm_melS.mean(), scores_rbf_svm_melS.std() * 2))

Accuracy: 0.32 (+/- 0.07)


## Prosodic Features

#### Path_to_Features for Loading

In [6]:
with open(path_to_data + 'Prosodic_Features/prosodic_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_pros= pickle.load(fp)
    
with open(path_to_data + 'Prosodic_Features/prosodic_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_pros= pickle.load(fp,encoding='latin1') 

In [7]:
X_profs = np.array(X_pros)
Y_prols = np.array(y_pros)

In [8]:
X_profs.shape, Y_prols.shape

((1574, 3), (1574,))

#### Splitting Data for TRAINing & TESTing

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_profs,Y_prols, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((1259, 3), (1259,), (315, 3), (315,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [ ]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm_pro =cross_val_score(clf_fold,X_profs,Y_prols, cv=10)

scores_lsvm_pro

In [ ]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm_pro.mean(), scores_lsvm_pro.std() * 2))

- Radial basis function - "rbf" Kernel

In [ ]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm_pros =cross_val_score(clf_rbf,X_melfs,Y_mels, cv=10)

scores_rbf_svm_pros

In [ ]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm_pros.mean(), scores_rbf_svm_pros.std() * 2))

## Transform the Matrix Shapes
  - XiV_features = np.array(X_iV).T
  - YiV_labels = np.array(Y_iV).T

Here, Tranform is being done to Reshape the Martix Shapes, Such that (#Samples, #features)

In [108]:
XiV_features = np.array(X_iV).T
YiV_labels = np.array(Y_iV).T

Here,below you can See the Difference:

In [91]:
XiV_features.shape, YiV_labels.shape

((400, 350), (400, 1))

In [111]:
YiV_labels = YiV_labels.reshape(400,);

#### Above Reshape() is used to Avoid this following Error
- /home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

## Models (for Classification of Dialects)
   - SVM
   - CNN