In [1]:
%config IPCompleter.greedy=True

In [2]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [3]:
import numpy as np
import pandas as pd
import sys
import pickle
import csv

In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

# Database_Sentence_Kannada_653_Samples

In [5]:
path_to_data = '/home/lenovo/All5_KannadaDataAug2018/5_Class_Sentc_Knd_Extracd_Features/'

max_classes = 5;
#Don't Edit this Below Code
max_classes += 1;

##### Read the file.csv  in Text Mode
- mode='rt' or mode='r'


Here, Read the file.csv  in Text Mode to Extract the Contents in it using above code.
      

In [5]:
X_mfcc = []
Y_mfcc = []

## CSV Not With PICKLE(PYTHON_eNCODING format)
- If the CSV file is Not Generated using PICKLE then to OPEN the file is the following way:

with open(path_to_data + 'MFCC_Features/MFCC_features_' + str(max_classes-1) + '.csv',mode='rt') as fp: 
    X_Mfccs= csv.reader(fp, delimiter=',',quotechar='|')
    
    for row in X_Mfccs:
        if len(row)!= 0:
            X_mfcc = X_mfcc + [row]
        
    print(fp.closed)
with open(path_to_data + 'MFCC_Features/MFCC_labels_' + str(max_classes-1) + '.csv',mode='rt') as fp:
    y_labels = csv.reader(fp, delimiter=',',quotechar='|')
    
    for row in y_labels:
        if len(row)!= 0:
            Y_mfcc = Y_mfcc + [row]
        
    print(fp.closed)

#### Error - while trying to Open a "(pickle)"- Encoded CSV file
 If U are trying to Open a "(pickle)"- Encoded CSV file, then this Error will Arise:
- UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte


## Opening CSV file Encoded using "PICKLE"_PYTHON Encoding

## MFCC__Features

#### Path_to_Features for Loading

In [6]:
with open(path_to_data + 'MFCC_Features/MFCC_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_mfcc= pickle.load(fp)

    
with open(path_to_data + 'MFCC_Features/MFCC_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_mfcc= pickle.load(fp,encoding='latin1') 

In [7]:
X_fs = np.array(X_mfcc)
Y_ls = np.array(y_mfcc)

In [8]:
X_fs.shape, Y_ls.shape

((653, 40), (653,))

#### Splitting Data for TRAINing & TESTing

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_fs,Y_ls, test_size=0.3,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((457, 40), (457,), (196, 40), (196,))

## DecisionTree Classifier 

- Random Forest

In [37]:
clrTree = DecisionTreeClassifier()

scores_dtree =cross_val_score(clrTree,X_fs,Y_ls, cv=2)

scores_dtree

array([ 0.82621951,  0.79076923])

In [38]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_dtree.mean(), scores_dtree.std() * 2))

Accuracy: 0.81 (+/- 0.04)


## KNN Classifier

In [39]:
clrKN = KNeighborsClassifier()

scores_clrKN =cross_val_score(clrKN,X_fs,Y_ls, cv=2)

scores_clrKN

array([ 0.93597561,  0.92615385])

In [41]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_clrKN.mean(), scores_clrKN.std() * 2))

Accuracy: 0.93 (+/- 0.01)


## Delta_mfcc Features Path

#### Path_to_Features for Loading

In [17]:
with open(path_to_data + 'MFCC_Features/delta_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_delta = pickle.load(fp)
with open(path_to_data + 'MFCC_Features/delta_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_delta = pickle.load(fp,encoding='latin1')

In [18]:
X_Dmfs = np.array(X_delta)
Y_Dls = np.array(y_delta)

In [19]:
X_Dmfs.shape, Y_Dls.shape

((653, 40), (653,))

# For Features (Mfcc+Delta_Mfcc)

In [20]:
X_mf_Dmfs=np.concatenate((X_fs,X_Dmfs),axis=1)

In [21]:
X_mf_Dmfs.shape

(653, 80)

#### Splitting Data for TRAINing & TESTing

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X_mf_Dmfs,Y_Dls, test_size=0.3,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((457, 80), (457,), (196, 80), (196,))

## Decision Tree Classifier

- Random Forest

In [42]:
clrDTree = DecisionTreeClassifier()

scores_DTree =cross_val_score(clrDTree,X_mf_Dmfs,Y_Dls, cv=2)

scores_DTree

array([ 0.84756098,  0.78769231])

In [43]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_DTree.mean(), scores_DTree.std() * 2))

Accuracy: 0.82 (+/- 0.06)


## KNN Classifier

In [44]:
clrKN_m_D = KNeighborsClassifier()

scores_KN_m_D =cross_val_score(clrKN_m_D,X_mf_Dmfs,Y_Dls, cv=2)

scores_KN_m_D

array([ 0.93597561,  0.92615385])

In [45]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_KN_m_D.mean(), scores_KN_m_D.std() * 2))

Accuracy: 0.93 (+/- 0.01)


## Delta_Delta_mfcc Features

#### Path_to_Features for Loading

In [27]:
with open(path_to_data + 'MFCC_Features/delta2_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_delta2 = pickle.load(fp)

with open(path_to_data + 'MFCC_Features/delta2_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_delta2 = pickle.load(fp,encoding='latin1')

In [28]:
X_DDmfs = np.array(X_delta2)
Y_DDls = np.array(y_delta2)

In [29]:
X_DDmfs.shape, Y_DDls.shape

((653, 40), (653,))

# For Features (Mfcc+Delta_mfcc + DDmfcc)

In [30]:
X_mfcc_Dmfc_DDmfc=np.concatenate((X_mf_Dmfs,X_DDmfs),axis=1)

In [31]:
X_mfcc_Dmfc_DDmfc.shape

(653, 120)

#### Splitting Data for TRAINing & TESTing

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X_mfcc_Dmfc_DDmfc,Y_DDls, test_size=0.5,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((326, 120), (326,), (327, 120), (327,))

## Decision Tree Classifier

- Random Forest

In [46]:
clr_DD_DTree = DecisionTreeClassifier()

scores_DD_DTree =cross_val_score(clr_DD_DTree,X_mfcc_Dmfc_DDmfc,Y_DDls, cv=2)

scores_DD_DTree

array([ 0.80792683,  0.81538462])

In [47]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_DD_DTree.mean(), scores_DD_DTree.std() * 2))

Accuracy: 0.81 (+/- 0.01)


## KNN Classifier

In [48]:
clrKN_m_D_DD = KNeighborsClassifier()

scores_KN_m_D_DD =cross_val_score(clrKN_m_D_DD,X_mfcc_Dmfc_DDmfc,Y_DDls, cv=2)

scores_KN_m_D_DD

array([ 0.93597561,  0.92615385])

In [49]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_KN_m_D_DD.mean(), scores_KN_m_D_DD.std() * 2))

Accuracy: 0.93 (+/- 0.01)


## MelSpectrogram Features

#### Path_to_Features for Loading

In [60]:
with open(path_to_data + 'MelSpec_Features/Mel_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_mel= pickle.load(fp)
    
with open(path_to_data + 'MelSpec_Features/Mel_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_mel= pickle.load(fp,encoding='latin1') 

In [61]:
X_melfs = np.array(X_mel)
Y_mels = np.array(y_mel)

In [62]:
X_melfs.shape, Y_mels.shape

((1574, 128), (1574,))

#### Splitting Data for TRAINing & TESTing

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X_melfs,Y_mels, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((1259, 128), (1259,), (315, 128), (315,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [65]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm =cross_val_score(clf_fold,X_melfs,Y_mels, cv=10)

scores_lsvm

array([ 0.3125    ,  0.24375   ,  0.3       ,  0.34591195,  0.29299363,
        0.32051282,  0.30128205,  0.35897436,  0.42580645,  0.33548387])

In [66]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm.mean(), scores_lsvm.std() * 2))

Accuracy: 0.32 (+/- 0.09)


- Radial basis function - "rbf" Kernel

In [69]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm_melS =cross_val_score(clf_rbf,X_melfs,Y_mels, cv=10)

scores_rbf_svm_melS

array([ 0.2875    ,  0.3       ,  0.28125   ,  0.41509434,  0.33121019,
        0.30769231,  0.30769231,  0.34615385,  0.30967742,  0.30967742])

In [70]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm_melS.mean(), scores_rbf_svm_melS.std() * 2))

Accuracy: 0.32 (+/- 0.07)


## Prosodic Features

#### Path_to_Features for Loading

In [36]:
with open(path_to_data + 'Prosodic_Features/prosodic_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_pros= pickle.load(fp)
    
with open(path_to_data + 'Prosodic_Features/prosodic_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_pros= pickle.load(fp,encoding='latin1') 

In [37]:
X_profs = np.array(X_pros)
Y_prols = np.array(y_pros)

In [38]:
X_profs.shape, Y_prols.shape

((680, 3), (680,))

#### Splitting Data for TRAINing & TESTing

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X_profs,Y_prols, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((544, 3), (544,), (136, 3), (136,))