In [94]:
%config IPCompleter.greedy=True

In [95]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.linear_model import SGDClassifier
import numpy as np
import pandas as pd
import sys
import pickle
import csv

# Database_Sentence_Kannada_653_Samples

In [4]:
path_to_data = '/home/lenovo/All5_KannadaDataAug2018/5_Class_Sentc_Knd_Extracd_Features/'

max_classes = 5;
#Don't Edit this Below Code
max_classes += 1;

##### Read the file.csv  in Text Mode
- mode='rt' or mode='r'


Here, Read the file.csv  in Text Mode to Extract the Contents in it using above code.
      

In [5]:
X_mfcc = []
Y_mfcc = []

## CSV Not With PICKLE(PYTHON_eNCODING format)
- If the CSV file is Not Generated using PICKLE then to OPEN the file is the following way:

with open(path_to_data + 'MFCC_Features/MFCC_features_' + str(max_classes-1) + '.csv',mode='rt') as fp: 
    X_Mfccs= csv.reader(fp, delimiter=',',quotechar='|')
    
    for row in X_Mfccs:
        if len(row)!= 0:
            X_mfcc = X_mfcc + [row]
        
    print(fp.closed)
with open(path_to_data + 'MFCC_Features/MFCC_labels_' + str(max_classes-1) + '.csv',mode='rt') as fp:
    y_labels = csv.reader(fp, delimiter=',',quotechar='|')
    
    for row in y_labels:
        if len(row)!= 0:
            Y_mfcc = Y_mfcc + [row]
        
    print(fp.closed)

#### Error - while trying to Open a "(pickle)"- Encoded CSV file
 If U are trying to Open a "(pickle)"- Encoded CSV file, then this Error will Arise:
- UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte


## Opening CSV file Encoded using "PICKLE"_PYTHON Encoding

## MFCC__Features

#### Path_to_Features for Loading

In [6]:
with open(path_to_data + 'MFCC_Features/MFCC_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_mfcc= pickle.load(fp)

    
with open(path_to_data + 'MFCC_Features/MFCC_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_mfcc= pickle.load(fp,encoding='latin1') 

In [7]:
X_fs = np.array(X_mfcc)
Y_ls = np.array(y_mfcc)

In [8]:
X_fs.shape, Y_ls.shape

((653, 40), (653,))

#### Splitting Data for TRAINing & TESTing

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_fs,Y_ls, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((522, 40), (522,), (131, 40), (131,))

### SGDClassifier Models (for Classification of Dialects)

- Loss = hinge

In [60]:
clf_fold = SGDClassifier(loss="hinge", penalty="l2")

scores_sgd_m_hinge =cross_val_score(clf_fold,X_fs,Y_ls, cv=10)

scores_sgd_m_hinge

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.75      ,  0.86363636,  0.78787879,  0.84848485,  0.75384615,
        0.73846154,  0.69230769,  0.84375   ,  0.703125  ,  0.71875   ])

In [61]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_sgd_m_hinge.mean(), scores_sgd_m_hinge.std() * 2))

Accuracy: 0.77 (+/- 0.12)


- loss = "log"

In [62]:
clf_Sgd_mh = SGDClassifier(loss="log", penalty="l2")

scores_Sgd_m_log =cross_val_score(clf_Sgd_mh,X_fs,Y_ls, cv=10)

scores_Sgd_m_log

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.75      ,  0.92424242,  0.8030303 ,  0.86363636,  0.87692308,
        0.76923077,  0.8       ,  0.859375  ,  0.796875  ,  0.765625  ])

In [63]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_Sgd_m_log.mean(), scores_Sgd_m_log.std() * 2))

Accuracy: 0.82 (+/- 0.11)


- loss = "modified_huber"

In [64]:
clf_Sgd_mh = SGDClassifier(loss="modified_huber", penalty="l2")

scores_Sgd_mh_m =cross_val_score(clf_Sgd_mh,X_fs,Y_ls, cv=10)

scores_Sgd_mh_m

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.79411765,  0.72727273,  0.77272727,  0.89393939,  0.75384615,
        0.78461538,  0.70769231,  0.859375  ,  0.734375  ,  0.828125  ])

In [65]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_Sgd_mh_m.mean(), scores_Sgd_mh_m.std() * 2))

Accuracy: 0.79 (+/- 0.11)


## Delta_mfcc Features Path

#### Path_to_Features for Loading

In [16]:
with open(path_to_data + 'MFCC_Features/delta_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_delta = pickle.load(fp)
with open(path_to_data + 'MFCC_Features/delta_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_delta = pickle.load(fp,encoding='latin1')

In [17]:
X_Dmfs = np.array(X_delta)
Y_Dls = np.array(y_delta)

In [18]:
X_Dmfs.shape, Y_Dls.shape

((653, 40), (653,))

# For Features (Mfcc+Delta_Mfcc)

In [19]:
with open(path_to_data + 'MFCC_Features/MFCC_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_mfcc_653 = pickle.load(fp)

In [20]:
X_mfc = np.array(X_mfcc_653)

In [21]:
X_mfc.shape

(653, 40)

In [22]:
X_mf_Dmfs=np.concatenate((X_mfc,X_Dmfs),axis=1)

#### Splitting Data for TRAINing & TESTing

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X_mf_Dmfs,Y_Dls, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((522, 80), (522,), (131, 80), (131,))

### SGD Models (for Classification of Dialects)

- Loss = "Log"

In [66]:
clf_fold = SGDClassifier(loss="log", penalty="l2")

scores_sgd =cross_val_score(clf_fold,X_mf_Dmfs,Y_Dls, cv=10)

scores_sgd

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.77941176,  0.95454545,  0.86363636,  0.86363636,  0.78461538,
        0.81538462,  0.70769231,  0.828125  ,  0.671875  ,  0.6875    ])

In [67]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_sgd.mean(), scores_sgd.std() * 2))

Accuracy: 0.80 (+/- 0.17)


- loss = "hinge"

In [68]:
clf_rbf = SGDClassifier(loss="hinge")

scores_hing_sgd_mplD =cross_val_score(clf_rbf,X_mf_Dmfs,Y_Dls, cv=10)

scores_hing_sgd_mplD

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.73529412,  0.75757576,  0.78787879,  0.78787879,  0.83076923,
        0.83076923,  0.76923077,  0.765625  ,  0.734375  ,  0.75      ])

In [69]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_hing_sgd_mplD.mean(), scores_hing_sgd_mplD.std() * 2))

Accuracy: 0.77 (+/- 0.07)


- loss = "modified_huber"

In [70]:
clf_rbf = SGDClassifier(loss="modified_huber")

scores_hing_sgdmh_mplD =cross_val_score(clf_rbf,X_mf_Dmfs,Y_Dls, cv=10)

scores_hing_sgdmh_mplD

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.60294118,  0.72727273,  0.78787879,  0.86363636,  0.76923077,
        0.93846154,  0.89230769,  0.765625  ,  0.65625   ,  0.75      ])

In [71]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_hing_sgdmh_mplD.mean(), scores_hing_sgdmh_mplD.std() * 2))

Accuracy: 0.78 (+/- 0.20)


## Delta_Delta_mfcc Features

#### Path_to_Features for Loading

In [30]:
with open(path_to_data + 'MFCC_Features/delta2_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_delta2 = pickle.load(fp)

with open(path_to_data + 'MFCC_Features/delta2_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_delta2 = pickle.load(fp,encoding='latin1')

In [31]:
X_DDmfs = np.array(X_delta2)
Y_DDls = np.array(y_delta2)

In [32]:
X_DDmfs.shape, Y_DDls.shape

((653, 40), (653,))

# For Features (Mfcc+Delta_mfcc + DDmfcc)

In [33]:
X_mfcc_Dmfc_DDmfc=np.concatenate((X_mf_Dmfs,X_DDmfs),axis=1)

In [34]:
X_mfcc_Dmfc_DDmfc.shape

(653, 120)

#### Splitting Data for TRAINing & TESTing

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X_mfcc_Dmfc_DDmfc,Y_DDls, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((522, 120), (522,), (131, 120), (131,))

### SGD Models (for Classification of Dialects)

- Loss = "modified_huber"

In [72]:
clf_fold = SGDClassifier(loss="modified_huber", penalty="l2")

scores_sgd_dd =cross_val_score(clf_fold,X_mfcc_Dmfc_DDmfc,Y_DDls, cv=10)

scores_sgd_dd

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.66176471,  0.68181818,  0.86363636,  0.8030303 ,  0.76923077,
        0.64615385,  0.72307692,  0.734375  ,  0.78125   ,  0.8125    ])

In [73]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_sgd_dd.mean(), scores_sgd_dd.std() * 2))

Accuracy: 0.75 (+/- 0.13)


- loss = "log"

In [74]:
clf_fold = SGDClassifier(loss="log", penalty="l2")

scores_sgd_dd_log =cross_val_score(clf_fold,X_mfcc_Dmfc_DDmfc,Y_DDls, cv=10)

scores_sgd_dd_log

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.82352941,  0.6969697 ,  0.66666667,  0.8030303 ,  0.76923077,
        0.83076923,  0.52307692,  0.796875  ,  0.75      ,  0.890625  ])

In [75]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_sgd_dd_log.mean(), scores_sgd_dd_log.std() * 2))

Accuracy: 0.76 (+/- 0.20)


- loss="hinge"

In [76]:
clf_fold = SGDClassifier(loss="hinge", penalty="l2")

scores_sgd_dd_log =cross_val_score(clf_fold,X_mfcc_Dmfc_DDmfc,Y_DDls, cv=10)

scores_sgd_dd_log

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.82352941,  0.84848485,  0.77272727,  0.75757576,  0.8       ,
        0.72307692,  0.76923077,  0.796875  ,  0.796875  ,  0.75      ])

In [77]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_sgd_dd_log.mean(), scores_sgd_dd_log.std() * 2))

Accuracy: 0.78 (+/- 0.07)


## All_Except_Chroma_Features

#### Path_to_Features for Loading

In [92]:
with open(path_to_data + 'All_Except_Chroma_Features/except_chroma_labels_' + str(max_classes-1) + '.txt',mode='rb') as fp: 
    y_all= pickle.load(fp)
    
with open(path_to_data + 'All_Except_Chroma_Features/except_chroma_features_X_new' + str(max_classes-1) + '.txt',mode='rb') as fp: 
    X_all= pickle.load(fp,encoding='latin1') 

- Radial basis function - "rbf" Kernel

In [93]:
clf_all = SGDClassifier(loss="hinge", penalty="l2")

scores_sgd_all_h =cross_val_score(clf_all,X_all,y_all, cv=10)

scores_sgd_all_h

ValueError: Found input variables with inconsistent numbers of samples: [637, 683]

In [30]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm.mean(), scores_rbf_svm.std() * 2))

Accuracy: 0.76 (+/- 0.11)


In [86]:
X_all

[array([[  2.40471869e-02,   1.72413793e-02,   1.58802178e-02, ...,
           8.16696915e-03,   1.86025408e-02,   3.22141561e-02],
        [  1.68778675e-02,   7.37040048e-03,   8.31024054e-03, ...,
           9.66581079e-04,   5.55297990e-04,   4.49725559e-04],
        [  2.97369922e+00,   3.19197880e+00,   2.90472162e+00, ...,
           3.21909251e+00,   2.97244791e+00,   2.97645357e+00],
        ..., 
        [  1.79875318e-02,   1.45783490e-01,   3.79068032e-02, ...,
           4.84266583e-03,   1.51398558e-02,   1.63656032e-02],
        [  3.70672870e-02,   2.66924747e-03,   1.77208357e-02, ...,
           6.86645891e-05,   2.38792455e-03,   1.07494336e-03],
        [  1.03696735e-02,   3.85997307e-02,   4.73118480e-02, ...,
           4.84414262e-02,   3.34017759e-02,   2.15835831e-02]]),
 array([[  1.36116152e-02,   9.07441016e-03,   9.07441016e-03, ...,
           6.21597096e-02,   2.90381125e-02,   2.81306715e-02],
        [  4.39759421e-02,   5.34347824e-02,   8.08581807e-0

In [62]:
X_melfs.shape, Y_mels.shape

((1574, 128), (1574,))

#### Splitting Data for TRAINing & TESTing

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X_melfs,Y_mels, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((1259, 128), (1259,), (315, 128), (315,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [65]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm =cross_val_score(clf_fold,X_melfs,Y_mels, cv=10)

scores_lsvm

array([ 0.3125    ,  0.24375   ,  0.3       ,  0.34591195,  0.29299363,
        0.32051282,  0.30128205,  0.35897436,  0.42580645,  0.33548387])

In [66]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm.mean(), scores_lsvm.std() * 2))

Accuracy: 0.32 (+/- 0.09)


- Radial basis function - "rbf" Kernel

In [69]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm_melS =cross_val_score(clf_rbf,X_melfs,Y_mels, cv=10)

scores_rbf_svm_melS

array([ 0.2875    ,  0.3       ,  0.28125   ,  0.41509434,  0.33121019,
        0.30769231,  0.30769231,  0.34615385,  0.30967742,  0.30967742])

In [70]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm_melS.mean(), scores_rbf_svm_melS.std() * 2))

Accuracy: 0.32 (+/- 0.07)


## Prosodic Features

#### Path_to_Features for Loading

In [81]:
with open(path_to_data + 'Prosodic_Features/prosodic_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_pros= pickle.load(fp)
    
with open(path_to_data + 'Prosodic_Features/prosodic_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_pros= pickle.load(fp,encoding='latin1') 

In [82]:
X_profs = np.array(X_pros)
Y_prols = np.array(y_pros)

In [83]:
X_profs.shape, Y_prols.shape

((680, 3), (680,))

#### Splitting Data for TRAINing & TESTing

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_profs,Y_prols, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((1259, 3), (1259,), (315, 3), (315,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [ ]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm_pro =cross_val_score(clf_fold,X_profs,Y_prols, cv=10)

scores_lsvm_pro

In [ ]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm_pro.mean(), scores_lsvm_pro.std() * 2))

- Radial basis function - "rbf" Kernel

In [ ]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm_pros =cross_val_score(clf_rbf,X_melfs,Y_mels, cv=10)

scores_rbf_svm_pros

In [ ]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm_pros.mean(), scores_rbf_svm_pros.std() * 2))

## Transform the Matrix Shapes
  - XiV_features = np.array(X_iV).T
  - YiV_labels = np.array(Y_iV).T

Here, Tranform is being done to Reshape the Martix Shapes, Such that (#Samples, #features)

In [108]:
XiV_features = np.array(X_iV).T
YiV_labels = np.array(Y_iV).T

Here,below you can See the Difference:

In [91]:
XiV_features.shape, YiV_labels.shape

((400, 350), (400, 1))

In [111]:
YiV_labels = YiV_labels.reshape(400,);

#### Above Reshape() is used to Avoid this following Error
- /home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

## Models (for Classification of Dialects)
   - SVM
   - CNN