# ensemble.GradientBoostingClassifier

In [1]:
%config IPCompleter.greedy=True

In [2]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [29]:
from sklearn import svm, ensemble, linear_model
import numpy as np
import pandas as pd
import sys
import pickle
import csv

# Database_Sentence_Kannada_653_Samples

In [4]:
path_to_data = '/home/lenovo/2019/Prathvi/NeuralNetwork/Project/Kannadaextracted_Features/splitmonodata/'

max_classes = 5;
#Don't Edit this Below Code
max_classes += 1;

##### Read the file.csv  in Text Mode
- mode='rt' or mode='r'


Here, Read the file.csv  in Text Mode to Extract the Contents in it using above code.
      

In [5]:
X_mfcc = []
Y_mfcc = []

## CSV Not With PICKLE(PYTHON_eNCODING format)
- If the CSV file is Not Generated using PICKLE then to OPEN the file is the following way:

with open(path_to_data + 'MFCC_Features/MFCC_features_' + str(max_classes-1) + '.csv',mode='rt') as fp: 
    X_Mfccs= csv.reader(fp, delimiter=',',quotechar='|')
    
    for row in X_Mfccs:
        if len(row)!= 0:
            X_mfcc = X_mfcc + [row]
        
    print(fp.closed)
with open(path_to_data + 'MFCC_Features/MFCC_labels_' + str(max_classes-1) + '.csv',mode='rt') as fp:
    y_labels = csv.reader(fp, delimiter=',',quotechar='|')
    
    for row in y_labels:
        if len(row)!= 0:
            Y_mfcc = Y_mfcc + [row]
        
    print(fp.closed)

#### Error - while trying to Open a "(pickle)"- Encoded CSV file
 If U are trying to Open a "(pickle)"- Encoded CSV file, then this Error will Arise:
- UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte


## Opening CSV file Encoded using "PICKLE"_PYTHON Encoding

## MFCC__Features

#### Path_to_Features for Loading

In [6]:
with open(path_to_data + 'MFCC_Features/MFCC_40_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_mfcc= pickle.load(fp)

    
with open(path_to_data + 'MFCC_Features/MFCC_40_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_mfcc= pickle.load(fp,encoding='latin1') 

In [7]:
X_fs = np.array(X_mfcc)
Y_ls = np.array(y_mfcc)

In [8]:
X_fs.shape, Y_ls.shape

((972, 40), (972,))

#### Splitting Data for TRAINing & TESTing

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_fs,Y_ls, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((777, 40), (777,), (195, 40), (195,))

### SGDClassifier Models (for Classification of Dialects)

- Loss = hinge

In [21]:
clf_fold = linear_model.SGDClassifier(loss="hinge", penalty="l2")

scores_sgd_m_hinge =cross_val_score(clf_fold,X_fs,Y_ls, cv=5)

scores_sgd_m_hinge

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.4822335 ,  0.46938776,  0.55958549,  0.48186528,  0.52331606])

In [41]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_sgd_m_hinge.mean()* 100, scores_sgd_m_hinge.std() * 200))

Accuracy: 50.33 (+/- 6.71)


- loss = "log"

In [23]:
clf_Sgd_mh = linear_model.SGDClassifier(loss="log", penalty="l2")

scores_Sgd_m_log =cross_val_score(clf_Sgd_mh,X_fs,Y_ls, cv=5)

scores_Sgd_m_log

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.50761421,  0.47959184,  0.58031088,  0.66839378,  0.53367876])

In [42]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_Sgd_m_log.mean()*100, scores_Sgd_m_log.std() * 200))

Accuracy: 55.39 (+/- 13.23)


- loss = "modified_huber"

In [26]:
clf_Sgd_mh = linear_model.SGDClassifier(loss="modified_huber", penalty="l2")

scores_Sgd_mh_m =cross_val_score(clf_Sgd_mh,X_fs,Y_ls, cv=5)

scores_Sgd_mh_m

/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/lenovo/ana

array([ 0.60913706,  0.39285714,  0.4611399 ,  0.59585492,  0.45595855])

In [43]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_Sgd_mh_m.mean() *100, scores_Sgd_mh_m.std() * 200))

Accuracy: 50.30 (+/- 16.97)


### SVM Models (for Classification of Dialects)

- Linear Kernel

In [30]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm =cross_val_score(clf_fold,X_fs,Y_ls,cv=5)

scores_lsvm

array([ 0.75634518,  0.7755102 ,  0.77202073,  0.74093264,  0.80310881])

In [36]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm.mean() * 100, scores_lsvm.std() * 200))

Accuracy: 76.96 (+/- 4.16)


- Radial basis function - "rbf" Kernel

In [39]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm_melS =cross_val_score(clf_rbf,X_fs,Y_ls, cv=5)

scores_rbf_svm_melS

array([ 0.2893401 ,  0.29081633,  0.30051813,  0.29015544,  0.30051813])

In [40]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm_melS.mean()* 100, scores_rbf_svm_melS.std() * 200))

Accuracy: 29.43 (+/- 1.02)


## Prosodic Features

#### Path_to_Features for Loading

In [81]:
with open(path_to_data + 'Prosodic_Features/prosodic_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_pros= pickle.load(fp)
    
with open(path_to_data + 'Prosodic_Features/prosodic_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_pros= pickle.load(fp,encoding='latin1') 

In [82]:
X_profs = np.array(X_pros)
Y_prols = np.array(y_pros)

In [83]:
X_profs.shape, Y_prols.shape

((680, 3), (680,))

#### Splitting Data for TRAINing & TESTing

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_profs,Y_prols, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((1259, 3), (1259,), (315, 3), (315,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [ ]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm_pro =cross_val_score(clf_fold,X_profs,Y_prols, cv=10)

scores_lsvm_pro

In [ ]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm_pro.mean(), scores_lsvm_pro.std() * 2))

- Radial basis function - "rbf" Kernel

In [ ]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm_pros =cross_val_score(clf_rbf,X_melfs,Y_mels, cv=10)

scores_rbf_svm_pros

In [ ]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm_pros.mean(), scores_rbf_svm_pros.std() * 2))

## Transform the Matrix Shapes
  - XiV_features = np.array(X_iV).T
  - YiV_labels = np.array(Y_iV).T

Here, Tranform is being done to Reshape the Martix Shapes, Such that (#Samples, #features)

In [108]:
XiV_features = np.array(X_iV).T
YiV_labels = np.array(Y_iV).T

Here,below you can See the Difference:

In [91]:
XiV_features.shape, YiV_labels.shape

((400, 350), (400, 1))

In [111]:
YiV_labels = YiV_labels.reshape(400,);

#### Above Reshape() is used to Avoid this following Error
- /home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

## Models (for Classification of Dialects)
   - SVM
   - CNN