In [1]:
%config IPCompleter.greedy=True

In [2]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [3]:
from sklearn import svm
import numpy as np
import pandas as pd
import sys
import pickle
import csv

# Database_Sentence_Kannada_680_Samples

In [4]:
path_to_data = '/home/lenovo/2019/Prathvi/NeuralNetwork/Project/Kannadaextracted_Features/splitmonodata/'

max_classes = 5;
#Don't Edit this Below Code
max_classes += 1;

##### Read the file.csv  in Text Mode
- mode='rt' or mode='r'


Here, Read the file.csv  in Text Mode to Extract the Contents in it using above code.
      

In [5]:
X_mfcc = []
Y_mfcc = []

## CSV Not With PICKLE(PYTHON_eNCODING format)
- If the CSV file is Not Generated using PICKLE then to OPEN the file is the following way:

with open(path_to_data + 'MFCC_Features/MFCC_features_' + str(max_classes-1) + '.csv',mode='rt') as fp: 
    X_Mfccs= csv.reader(fp, delimiter=',',quotechar='|')
    
    for row in X_Mfccs:
        if len(row)!= 0:
            X_mfcc = X_mfcc + [row]
        
    print(fp.closed)
with open(path_to_data + 'MFCC_Features/MFCC_labels_' + str(max_classes-1) + '.csv',mode='rt') as fp:
    y_labels = csv.reader(fp, delimiter=',',quotechar='|')
    
    for row in y_labels:
        if len(row)!= 0:
            Y_mfcc = Y_mfcc + [row]
        
    print(fp.closed)

#### Error - while trying to Open a "(pickle)"- Encoded CSV file
 If U are trying to Open a "(pickle)"- Encoded CSV file, then this Error will Arise:
- UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte


## Opening CSV file Encoded using "PICKLE"_PYTHON Encoding

## MFCC__Features

#### Path_to_Features for Loading

In [7]:
with open(path_to_data + 'MFCC_Features/MFCC_40_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_mfcc= pickle.load(fp)

    
with open(path_to_data + 'MFCC_Features/MFCC_40_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_mfcc= pickle.load(fp,encoding='latin1') 

In [8]:
X_fs = np.array(X_mfcc)
Y_ls = np.array(y_mfcc)

In [9]:
X_fs.shape, Y_ls.shape

((972, 40), (972,))

#### Splitting Data for TRAINing & TESTing

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X_fs,Y_ls, test_size=0.3,  random_state=5)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((680, 40), (680,), (292, 40), (292,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [12]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm =cross_val_score(clf_fold,X_fs,Y_ls, cv=5)

scores_lsvm

array([ 0.75634518,  0.7755102 ,  0.77202073,  0.74093264,  0.80310881])

In [13]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm.mean(), scores_lsvm.std() * 2))

Accuracy: 0.77 (+/- 0.04)


- Radial basis function - "rbf" Kernel

In [14]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm =cross_val_score(clf_rbf,X_fs,Y_ls, cv=10)

scores_rbf_svm

array([ 0.3       ,  0.3       ,  0.28571429,  0.28571429,  0.28571429,
        0.29896907,  0.29166667,  0.29473684,  0.31578947,  0.29473684])

In [15]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm.mean(), scores_rbf_svm.std() * 2))

Accuracy: 0.30 (+/- 0.02)


## Delta_mfcc Features Path

#### Path_to_Features for Loading

In [14]:
with open(path_to_data + 'MFCC_Features/delta_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_delta = pickle.load(fp)
with open(path_to_data + 'MFCC_Features/delta_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_delta = pickle.load(fp,encoding='latin1')

In [15]:
X_Dmfs = np.array(X_delta)
Y_Dls = np.array(y_delta)

In [16]:
X_Dmfs.shape, Y_Dls.shape

((653, 40), (653,))

#### Splitting Data for TRAINing & TESTing

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X_Dmfs,Y_Dls, test_size=0.,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((457, 40), (457,), (196, 40), (196,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [19]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm =cross_val_score(clf_fold,X_fs,Y_ls, cv=10)

scores_lsvm

array([ 0.88571429,  0.94202899,  0.95652174,  0.92753623,  0.95588235,
        0.95588235,  0.97014925,  0.95522388,  0.89552239,  0.89393939])

In [20]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm.mean(), scores_lsvm.std() * 2))

Accuracy: 0.93 (+/- 0.06)


- Radial basis function - "rbf" Kernel

In [21]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm =cross_val_score(clf_rbf,X_Dmfs,Y_Dls, cv=10)

scores_rbf_svm

array([ 0.67647059,  0.84848485,  0.74242424,  0.78787879,  0.78461538,
        0.78461538,  0.81538462,  0.703125  ,  0.71875   ,  0.703125  ])

In [22]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm.mean(), scores_rbf_svm.std() * 2))

Accuracy: 0.76 (+/- 0.11)


## Delta_Delta_mfcc Features

#### Path_to_Features for Loading

In [23]:
with open(path_to_data + 'MFCC_Features/delta2_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_delta2 = pickle.load(fp)

with open(path_to_data + 'MFCC_Features/delta2_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_delta2 = pickle.load(fp,encoding='latin1')

In [24]:
X_DDmfs = np.array(X_delta2)
Y_DDls = np.array(y_delta2)

In [25]:
X_DDmfs.shape, Y_DDls.shape

((653, 40), (653,))

#### Splitting Data for TRAINing & TESTing

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X_DDmfs,Y_DDls, test_size=0.3,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((457, 40), (457,), (196, 40), (196,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [27]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm =cross_val_score(clf_fold,X_DDmfs,Y_DDls, cv=10)

scores_lsvm

array([ 0.72058824,  0.84848485,  0.87878788,  0.75757576,  0.73846154,
        0.86153846,  0.8       ,  0.734375  ,  0.78125   ,  0.703125  ])

In [28]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm.mean(), scores_lsvm.std() * 2))

Accuracy: 0.78 (+/- 0.12)


- Radial basis function - "rbf" Kernel

In [29]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm =cross_val_score(clf_rbf,X_Dmfs,Y_Dls, cv=10)

scores_rbf_svm

array([ 0.67647059,  0.84848485,  0.74242424,  0.78787879,  0.78461538,
        0.78461538,  0.81538462,  0.703125  ,  0.71875   ,  0.703125  ])

In [30]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm.mean(), scores_rbf_svm.std() * 2))

Accuracy: 0.76 (+/- 0.11)


## MelSpectrogram Features

#### Path_to_Features for Loading

In [60]:
with open(path_to_data + 'MelSpec_Features/Mel_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_mel= pickle.load(fp)
    
with open(path_to_data + 'MelSpec_Features/Mel_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_mel= pickle.load(fp,encoding='latin1') 

In [61]:
X_melfs = np.array(X_mel)
Y_mels = np.array(y_mel)

In [62]:
X_melfs.shape, Y_mels.shape

((1574, 128), (1574,))

#### Splitting Data for TRAINing & TESTing

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X_melfs,Y_mels, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((1259, 128), (1259,), (315, 128), (315,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [65]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm =cross_val_score(clf_fold,X_melfs,Y_mels, cv=10)

scores_lsvm

array([ 0.3125    ,  0.24375   ,  0.3       ,  0.34591195,  0.29299363,
        0.32051282,  0.30128205,  0.35897436,  0.42580645,  0.33548387])

In [66]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm.mean(), scores_lsvm.std() * 2))

Accuracy: 0.32 (+/- 0.09)


- Radial basis function - "rbf" Kernel

In [69]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm_melS =cross_val_score(clf_rbf,X_melfs,Y_mels, cv=10)

scores_rbf_svm_melS

array([ 0.2875    ,  0.3       ,  0.28125   ,  0.41509434,  0.33121019,
        0.30769231,  0.30769231,  0.34615385,  0.30967742,  0.30967742])

In [70]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm_melS.mean(), scores_rbf_svm_melS.std() * 2))

Accuracy: 0.32 (+/- 0.07)


## Prosodic Features

#### Path_to_Features for Loading

In [44]:
with open(path_to_data + 'Prosodic_Features/prosodic_labels_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    y_pros= pickle.load(fp)
    
with open(path_to_data + 'Prosodic_Features/prosodic_features_' + str(max_classes-1) + '.csv',mode='rb') as fp: 
    X_pros= pickle.load(fp,encoding='latin1') 

In [45]:
X_profs = np.array(X_pros)
Y_prols = np.array(y_pros)

In [46]:
X_profs.shape, Y_prols.shape

((680, 3), (680,))

#### Splitting Data for TRAINing & TESTing

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X_profs,Y_prols, test_size=0.2,  random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((544, 3), (544,), (136, 3), (136,))

### SVM Models (for Classification of Dialects)

- Linear Kernel

In [48]:
clf_fold = svm.SVC(kernel='linear', C=1)

scores_lsvm_pro =cross_val_score(clf_fold,X_profs,Y_prols, cv=10)

scores_lsvm_pro

array([ 0.45714286,  0.42028986,  0.43478261,  0.47826087,  0.5       ,
        0.5       ,  0.49253731,  0.46268657,  0.50746269,  0.56060606])

In [49]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_lsvm_pro.mean(), scores_lsvm_pro.std() * 2))

Accuracy: 0.48 (+/- 0.08)


- Radial basis function - "rbf" Kernel

In [ ]:
clf_rbf = svm.SVC(kernel='rbf', C=1)

scores_rbf_svm_pros =cross_val_score(clf_rbf,X_melfs,Y_mels, cv=10)

scores_rbf_svm_pros

In [ ]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_rbf_svm_pros.mean(), scores_rbf_svm_pros.std() * 2))

## Transform the Matrix Shapes
  - XiV_features = np.array(X_iV).T
  - YiV_labels = np.array(Y_iV).T

Here, Tranform is being done to Reshape the Martix Shapes, Such that (#Samples, #features)

In [108]:
XiV_features = np.array(X_iV).T
YiV_labels = np.array(Y_iV).T

Here,below you can See the Difference:

In [91]:
XiV_features.shape, YiV_labels.shape

((400, 350), (400, 1))

In [111]:
YiV_labels = YiV_labels.reshape(400,);

#### Above Reshape() is used to Avoid this following Error
- /home/lenovo/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)